# Number of seconds a test session will wait to acquire the necessary
# actors before it is cancelled
acquireActorsTimeoutSec: 1200

# Number of seconds a test session will be cancelled after, when there is
# no activity (no actors are making any progress executing test steps)
noActivityTimeoutSec: 3600

# The path to the root of the test repository directory. If you're using
# backslash characters, make sure to escape them (e.g. "C:\\test-defs")
testRepoDir: "../test-defs"