# Number of seconds a test session will wait to acquire the necessary
# actors before it is cancelled
acquireActorsTimeoutSec: 1200

# Number of seconds a test session will be cancelled after, when there is
# no activity (no actors are making any progress executing test steps)
noActivityTimeoutSec: 3600

# The path where the test repository directory resides. If empty or ".", the
# test repo will be located in the root of the sync service project
testRepoLocation: "."

testRepoDirName: "test-defs"